name: Update Products and Deploy

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜執行
  workflow_dispatch:      # 允許手動觸發
  push:
    branches: [ "main" ]  # 當推送到主分支時也執行

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
        
    - name: Run product generation script
      run: |
        python scripts/generate_products.py
      env:
        PYTHONUNBUFFERED: 1
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/product.js
        git commit -m "Update product.js" || echo "No changes to commit"
        git push
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3

permissions:
  contents: write
  pages: write
  id-token: write
